import type { NotesFolderNode } from "@/lib/notes-types"

const D = "2026-08-07"

export const gradRoadmapTree: NotesFolderNode = {
  type: "folder",
  id: "grad-project-roadmap",
  name: "Grad project roadmap",
  createdAt: D,
  updatedAt: D,
  children: [
    {
      type: "file",
      id: "grad-start-beginner",
      name: "Start here (beginner)",
      createdAt: D,
      updatedAt: D,
    },
    {
      type: "file",
      id: "grad-start-intermediate",
      name: "Start here (intermediate)",
      createdAt: D,
      updatedAt: D,
    },
    {
      type: "file",
      id: "grad-jump-project",
      name: "Jump here (the project)",
      createdAt: D,
      updatedAt: D,
    },
    {
      type: "folder",
      id: "grad-00-tools",
      name: "00 · Tools setup",
      createdAt: D,
      updatedAt: D,
      children: [
        {
          type: "file",
          id: "grad-vscode-setup",
          name: "Install VS Code",
          createdAt: D,
          updatedAt: D,
        },
        {
          type: "file",
          id: "grad-node-setup",
          name: "Install Node.js",
          createdAt: D,
          updatedAt: D,
        },
      ],
    },
    {
      type: "folder",
      id: "grad-01-git",
      name: "01 · Git & GitHub",
      createdAt: D,
      updatedAt: D,
      children: [
        {
          type: "file",
          id: "grad-git-overview",
          name: "What Git does",
          createdAt: D,
          updatedAt: D,
        },
        {
          type: "file",
          id: "grad-github-setup",
          name: "GitHub account & clone",
          createdAt: D,
          updatedAt: D,
        },
        {
          type: "file",
          id: "grad-git-first-repo",
          name: "First repo (hands on)",
          createdAt: D,
          updatedAt: D,
        },
        {
          type: "file",
          id: "grad-git-branches",
          name: "Branches & merge",
          createdAt: D,
          updatedAt: D,
        },
      ],
    },
    {
      type: "folder",
      id: "grad-02-web",
      name: "02 · HTML, CSS & JS",
      createdAt: D,
      updatedAt: D,
      children: [
        {
          type: "file",
          id: "grad-web-html-css",
          name: "HTML & CSS skeleton",
          createdAt: D,
          updatedAt: D,
        },
        {
          type: "file",
          id: "grad-web-javascript",
          name: "JavaScript basics",
          createdAt: D,
          updatedAt: D,
        },
        {
          type: "file",
          id: "grad-web-mini-project",
          name: "Mini landing page",
          createdAt: D,
          updatedAt: D,
        },
      ],
    },
    {
      type: "folder",
      id: "grad-03-react",
      name: "03 · React",
      createdAt: D,
      updatedAt: D,
      children: [
        {
          type: "file",
          id: "grad-react-concepts",
          name: "Mental model",
          createdAt: D,
          updatedAt: D,
        },
        {
          type: "file",
          id: "grad-react-scaffold",
          name: "Scaffold the app",
          createdAt: D,
          updatedAt: D,
        },
        {
          type: "file",
          id: "grad-react-build-ui",
          name: "Build the UI",
          createdAt: D,
          updatedAt: D,
        },
        {
          type: "file",
          id: "grad-react-data",
          name: "State & data flow",
          createdAt: D,
          updatedAt: D,
        },
      ],
    },
    {
      type: "folder",
      id: "grad-04-nextjs",
      name: "04 · Next.js",
      createdAt: D,
      updatedAt: D,
      children: [
        {
          type: "file",
          id: "grad-next-why",
          name: "Why Next.js",
          createdAt: D,
          updatedAt: D,
        },
        {
          type: "file",
          id: "grad-next-app-router",
          name: "App Router tour",
          createdAt: D,
          updatedAt: D,
        },
        {
          type: "file",
          id: "grad-next-api",
          name: "API routes & data",
          createdAt: D,
          updatedAt: D,
        },
      ],
    },
    {
      type: "folder",
      id: "grad-05-mongodb",
      name: "05 · MongoDB",
      createdAt: D,
      updatedAt: D,
      children: [
        {
          type: "file",
          id: "grad-mongo-install",
          name: "Install MongoDB",
          createdAt: D,
          updatedAt: D,
        },
        {
          type: "file",
          id: "grad-mongo-connect",
          name: "Connect from Next.js",
          createdAt: D,
          updatedAt: D,
        },
        {
          type: "file",
          id: "grad-mongo-in-project",
          name: "Repo pattern in the project",
          createdAt: D,
          updatedAt: D,
        },
      ],
    },
    {
      type: "folder",
      id: "grad-06-structure",
      name: "06 · Codebase structure",
      createdAt: D,
      updatedAt: D,
      children: [
        {
          type: "file",
          id: "grad-structure-features",
          name: "Feature folders",
          createdAt: D,
          updatedAt: D,
        },
        {
          type: "file",
          id: "grad-structure-layers",
          name: "Components, hooks, utils, actions",
          createdAt: D,
          updatedAt: D,
        },
        {
          type: "file",
          id: "grad-structure-tour",
          name: "Grad repo tour",
          createdAt: D,
          updatedAt: D,
        },
        {
          type: "file",
          id: "grad-structure-portfolio",
          name: "Portfolio feature deep dive",
          createdAt: D,
          updatedAt: D,
        },
      ],
    },
  ],
}
